version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

executors:
  ci-container:
    docker:
      - image: jadomage/ci-gcc-nasm-cmake-lcov:0.0.3

jobs:
  config:
    executor: ci-container
    steps:
      - checkout
      - run: cmake . -DAUDIO=OFF -DENGINE=OFF -DCODE_COVERAGE=ON
  build:
    executor: ci-container
    steps:
      - run: make
  test:
    executor: ci-container
    steps:
      - run: make test
  coverage:
    executor: ci-container
    steps:
      - run: lcov --capture --directory . --output-file coverage.info
      - run: lcov --remove coverage.info '/usr/*' --output-file coverage.info
      - run: lcov --list coverage.info
      - codecov/upload:
          file: coverage.info
