version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
    - image: rpgillespie6/fastcov:latest # the primary container, where your job's commands are run
    steps:
    - checkout # check out the code in the project directory
    - run: cmake . -DAUDIO=OFF -DENGINE=OFF -DCODE_COVERAGE=ON # run the `echo` command
    - run: make
    - run: make test
    - run: lcov --capture --directory . --output-file coverage.info
    - run: lcov --remove coverage.info '/usr/*' --output-file coverage.info
    - run: lcov --list coverage.info
    - codecov/upload:
        file: coverage.info
