version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

executors:
  ci-container:
    docker:
      - image: jadomage/ci-gcc-nasm-cmake-lcov:0.0.3

jobs:
  build:
    executor: ci-container
    steps:
      - checkout
      - run: cmake . -D NETERO_AUDIO=OFF -DNETERO_GRAPHICS=OFF
      - run: make
  test:
    executor: ci-container
    steps:
      - checkout
      - run: cmake . -D NETERO_AUDIO=OFF -DNETERO_GRAPHICS=OFF -D CODE_COVERAGE=ON
      - run: make
      - run: make test
      - run: lcov --capture --directory . --output-file coverage.info
      - run: lcov --remove coverage.info '/usr/*' --output-file coverage.info
      - run: lcov --list coverage.info
      - codecov/upload:
          file: coverage.info

workflows:
  version: 2
  unit_test:
    jobs:
      - test
